### PR TITLE
Handle network disconnection

### LINKED ISSUE #43: Cody: Handle network error disconnection
When there's any network error during the chat session, it shows unexpected error.

iScreen Shoter - Code - 230622122045
iScreen Shoter - Code - 230622121847

Expected behaviour:
1. If there's a network error when users load the extension and have a valid token. Add an error message that "Could not load Cody due to network error" with a reload button to attempt when the connection is back.
2. If a network error happens during the chat, stop the execution and show an error message in the web view "Network error occurred; try after some time".

### PR DESCRIPTION
**Pull request by deepak2431**
This PR closes #43. It handles the network error for the DOTCOM instance. It handles the server disconnection due to network issues by adding an appropriate message. Also, add a reload button to return when the user is back in the network.

# Test plan

All tests have passed.

https://github.com/sourcegraph/cody/assets/44617923/6becbe05-3d24-456a-9a1e-caf7f4fa04c6

### CODE REVIEW

**Comment by deepak2431** [comment]
@abeatrix Can I have a review, please?

File: vscode/src/chat/ChatViewProvider.ts [hunk 1]
```diff
@@ -263,9 +263,12 @@ export class ChatViewProvider implements vscode.WebviewViewProvider, vscode.Disp
                 // cody.auth.signin or cody.auth.signout
                 await vscode.commands.executeCommand(`cody.auth.${message.type}`)
                 break
-            case 'settings':
-                await this.authProvider.auth(message.serverEndpoint, message.accessToken, this.config.customHeaders)
+            case 'settings': {
+                const endpoint = message.serverEndpoint.length ? message.serverEndpoint : this.config.serverEndpoint
```
Comment (abeatrix) [inline vscode/src/chat/ChatViewProvider.ts:267]: Can you tell me more about this change? 
This is called when a user input the endpoint and access token manually, so it doesn't make sense to me to replace them with the ones from this.config if those are not available 👀

File: vscode/src/chat/ChatViewProvider.ts [hunk 2]
```diff
@@ -386,8 +389,18 @@ export class ChatViewProvider implements vscode.WebviewViewProvider, vscode.Disp
                 if (isAbortError(err)) {
                     return
                 }
+                // check first if search error is due to any network issue
+                if (isNetworkError(err)) {
+                    void this.sendErrorToWebview(
```
Comment (abeatrix) [inline vscode/src/chat/ChatViewProvider.ts:394]: i think instead of `this.sendErrorToWebview()`, we should use `this.transcript.addErrorAsAssistantResponse()` (or both) to avoid having missing bot response item: 
image

 i think the only time we can have a boy response item is when the message is aborted manually, what do you think? 😄

File: vscode/webviews/Error.tsx [hunk 3]
```diff
@@ -45,6 +52,25 @@ export const ErrorContainer: React.FunctionComponent<{
...
+    const handleReload = (): void => {
+        getVSCodeAPI().postMessage({ command: 'settings', serverEndpoint: '', accessToken: '' })
+    }
+
+    // When there's a network error
+    if (showNetworkError) {
+        return (
+            <>
+                <div className={styles.error}>
+                    <p>{AUTH_ERRORS.NETWORK_ERROR}</p>
```
Comment (abeatrix) [inline vscode/webviews/Error.tsx:65]: I like this! Maybe we can show the endpoint address to let the user know which instance is having network issue?

File: vscode/webviews/Error.tsx [hunk 4]
```diff
@@ -45,6 +52,25 @@ export const ErrorContainer: React.FunctionComponent<{
...
+                    <VSCodeButton className={styles.button} type="button" onClick={handleReload}>
```
Comment (abeatrix) [inline vscode/webviews/Error.tsx:66]: maybe update the button styles to have full width like the rest of the buttons in the login page? Will defer to @toolmantim who will be back next week from his PTO :)

Comment (abeatrix) [inline vscode/webviews/Error.tsx:66]: maybe update the button styles to have full width like the rest of the buttons in the login page? Will defer to @toolmantim who will be back next week from his PTO :)

**Review by abeatrix — CHANGES_REQUESTED** [review]
i left some comments inline with some minor change request, the rest looks good to me!
Will defer to tim on the design :D

File: vscode/webviews/Error.tsx (hunk 4 above)
Comment (deepak2431) [reply vscode/webviews/Error.tsx:66]: Yes, we can have that so it would be align to the style with all other buttons.

File: vscode/webviews/Error.tsx (hunk 3 above)
Comment (deepak2431) [reply vscode/webviews/Error.tsx:65]: That would be a good add on, I will update it.

File: vscode/src/chat/ChatViewProvider.ts (hunk 2 above)
Comment (deepak2431) [reply vscode/src/chat/ChatViewProvider.ts:394]: It would be good to have both of them, as ENOTFOUND error as error assistant response shows up. So, this won't be much clear for the user as to why this is happening, so it would be better to include both. LMK, if you agree to this?

**Comment by deepak2431** [comment]
@abeatrix Thanks for the review! Can network errors be handled when the Sign In is done using Cody App? I tried this but couldn't get a working solution. 
Also, do you mind testing it once for the enterprise test customer instance to ensure it works perfectly for that cases too?

File: vscode/src/chat/ChatViewProvider.ts (hunk 2 above)
Comment (abeatrix) [reply vscode/src/chat/ChatViewProvider.ts:394]: Yea let's see what tim thinks but what what you suggested makes sense to me :)

Comment (deepak2431) [reply vscode/src/chat/ChatViewProvider.ts:394]: Sure, will wait for him to confirm.

**Comment by deepak2431** [comment]
@toolmantim Can you please look at this and add your comments about the flow and the button CSS so I can make those changes?

File: vscode/webviews/Error.tsx (hunk 4 above)
Comment (deepak2431) [reply vscode/webviews/Error.tsx:66]: Got it, thanks @toolmantim

File: vscode/src/chat/ChatViewProvider.ts (hunk 2 above)
Comment (deepak2431) [reply vscode/src/chat/ChatViewProvider.ts:394]: @toolmantim  What about this?

Comment (toolmantim) [reply vscode/src/chat/ChatViewProvider.ts:394]: I think outputting it into the chat as a bot response is enough, we don't need an additional error at the top also. We could restyle the error bot responses to be red or make it clearer, but that can happen in a follow-up.

Comment (deepak2431) [reply vscode/src/chat/ChatViewProvider.ts:394]: That sounds good to me. To mention, for now, there's an implementation of ErrAssistantResponse to show in the chat so after removing this webview error that would be displayed in case of an error.

**Comment by abeatrix** [comment]
Left an in-line comment. Also adding @umpox as reviewer as he's working on refactoring the chat view that could be related 😃

**Comment by deepak2431** [comment]
@abeatrix I think you forgot to submit the inline comments as I can't see them. Looking forward to review from @umpox

**Review by abeatrix — COMMENTED** [review]
See inline comment.
Will defer to @umpox for final approval as this made changes in the refactoring work he is working on.

File: vscode/src/chat/ChatViewProvider.ts [hunk 5]
```diff
@@ -278,9 +278,12 @@ export class ChatViewProvider implements vscode.WebviewViewProvider, vscode.Disp
                 // cody.auth.signin or cody.auth.signout
                 await vscode.commands.executeCommand(`cody.auth.${message.type}`)
                 break
-            case 'settings':
-                await this.authProvider.auth(message.serverEndpoint, message.accessToken, this.config.customHeaders)
+            case 'settings': {
+                const endpoint = message.serverEndpoint.length ? message.serverEndpoint : this.config.serverEndpoint
+                const token = message.accessToken.length ? message.accessToken : this.config.accessToken
```
[the remark this answers is not in the document]
Comment (deepak2431) [reply vscode/src/chat/ChatViewProvider.ts:283]: Yeah, agree that would be the case here based on the implementation logic. It would be better to separate this in different messages as `reload`, in which we check the config values and` login` the user. WDYT, LMK?

File: vscode/webviews/Error.tsx [hunk 6]
```diff
@@ -10,6 +14,8 @@ const AUTH_ERRORS = {
     EMAIL_NOT_VERIFIED: 'Email not verified. Please add a verified email to your Sourcegraph.com account.',
     APP_NOT_RUNNING: 'Cody App is not running. Please open the Cody App to continue.',
     INVALID_URL: 'Connection failed due to invalid URL. Please enter a valid Sourcegraph instance URL.',
+    NETWORK_ERROR:
+        'Due to network-related problems, Cody cannot be reached. Try again after checking it! Once your connection is restored, attempt a reload.',
```
Comment (umpox) [inline vscode/webviews/Error.tsx:18]:
```suggestion
    NETWORK_ERROR:
        'Connection failed due to a network problem. Please check your internet connection and try again.',
```

Small copy change to make this a bit simpler

File: vscode/src/chat/ChatViewProvider.ts (hunk 5 above)
[the remark this answers is not in the document]
Comment (umpox) [reply vscode/src/chat/ChatViewProvider.ts:283]: I think separating this into `reload` is a good idea 👍

**Review by umpox — COMMENTED** [review]
Left a couple of comments!

**Comment by deepak2431** [comment]
@umpox @abeatrix Made all the requested changes. Also, I updated the error message in the assistant response in case of network error to be clear about that. Check the updated video in the PR description for the final behaviour.

**Comment by abeatrix** [comment]
@deepak2431 

> @umpox @abeatrix Made all the requested changes. Also, I updated the error message in the assistant response in case of network error to be clear about that. Check the updated video in the PR description for the final behaviour.

can you resolve the merge conflicts before we check out the branch please? Thanks!

**Comment by deepak2431** [comment]
@abeatrix Resolved the conflicts and updated the code as per the refactor of ChatView.

**Review by abeatrix — APPROVED** [review]
worked as expected! Thanks @deepak2431 !!

**Review by umpox — APPROVED** [review]
🚀
