### PR TITLE
Fix already disposed error from WebviewViewManager (closes #3040)

### LINKED ISSUE #3040: Enterprise users can see all the projects that their admin has given to Cody as context (including projects that are in the process of being indexed for embedding, graph, or local context)

### PR DESCRIPTION
**Pull request by mkondratek**
Fixes #3040
Fixes #2660

## Test plan
unable to reproduce

### CODE REVIEW

File: jetbrains/src/main/kotlin/com/sourcegraph/utils/CodyEditorUtil.kt [hunk 1]
```diff
@@ -78,6 +78,7 @@ object CodyEditorUtil {
 
   @JvmStatic
   fun getSelectedEditors(project: Project): Array<out Editor> {
+    if (project.isDisposed) return emptyArray()
```
Comment (mkondratek) [inline jetbrains/src/main/kotlin/com/sourcegraph/utils/CodyEditorUtil.kt:81]: #2660

**Review by tomaszgolebiowski — APPROVED** [review]
